#!/bin/bash


# ------------------------------------------------------------------
# # # # # # #
# CORE
# # # # # # #
# ------------------------------------------------------------------


# hushlogin-type implementation to hide script usage

KILLSWITCH="$HOME/.waifulock"
if [[ -f "$KILLSWITCH" ]]; then
  echo "This command does nothing. Have a wonderful day!"
  exit 0
fi


SCRIPT="$(basename "$0")" # grab script name

print_err_msg() {
  echo "$SCRIPT: $1" >&2
  exit "${2:-1}"
}


# ------------------------------------------------------------------
# # # # # # #
# FUNCTIONS
# # # # # # #
# ------------------------------------------------------------------

print_help() {
  printf '%s\n' "
$SCRIPT is a simple CLI tool: view or download random waifu images from waifu.im.

Docs:
  $SCRIPT --help: Show this help screen
  $SCRIPT --nsfw help: Show nsfw help screen
  $SCRIPT --view help: Show image viewer help screen
  $SCRIPT --id help: Show id lookup help screen
  $SCRIPT --tag help: Show tag lookup help screen
  $SCRIPT --type help: Show type sort help screen
  $SCRIPT --sort help: Show sort type help screen

Usage examples:
  $SCRIPT -ne -o animegirl.png [ Set mode to only NSFW and save the image to ./animegirl.png ]
  $SCRIPT -nb -t [ Set mode to all (NSFW+SFW) and open it with termux-open, for termux users. ]
  $SCRIPT -ne -vc [ Set mode to only NSFW and view the image with chafa ]
  $SCRIPT -p [ Print image URL ]
  $SCRIPT -vc -ne -ghentai [ Set mode to only NSFW, search the tag hentai and view the image with chafa ]
  $SCRIPT -vc -nn -gwaifu [ Set mode to no NSFW, search the tag waifu and view the image with chafa ]
  
# -g is equivalent to --tag
# -a is equivalent to --type

Valid flags:

Short:
  $SCRIPT -h
  $SCRIPT -p
  $SCRIPT -t

  $SCRIPT -o (arg required)
  $SCRIPT -n (arg required)
  $SCRIPT -v (arg required)
  $SCRIPT -i (arg required)
  $SCRIPT -g (arg required)
  $SCRIPT -a (arg required)
  $SCRIPT -s (arg required)
Long:
  $SCRIPT --help
  $SCRIPT --termux
  $SCRIPT --print

  $SCRIPT --output (arg required)
  $SCRIPT --nsfw (arg required)
  $SCRIPT --view (arg required)
  $SCRIPT --id (arg required)
  $SCRIPT --tag (arg required)
  $SCRIPT --type (arg required)
  $SCRIPT --sort (arg required)
"
}

name_valid() {
  local XD
  local -n X_ARR="$1"

  for XD in "${X_ARR[@]}"; do
    [[ "$XD" == "$2" ]] && return 0
  done
  return 1
}

nsfw_valid() {
  name_valid NSFW_VALID "$1" && \
    return 0
  return 1
}

view_valid() {
  name_valid VIEW_VALID "$1" && \
    return 0
  return 1
}

tag_valid() {
  name_valid TAG_VALID "$1" && \
    return 0
  return 1
}

type_valid() {
  name_valid TYPE_VALID "$1" && \
    return 0
  return 1
}

sort_valid() {
  name_valid SORT_VALID "$1" && \
    return 0
  return 1
}

# ------------------------------------------------------------------
# # # # # # #
# VARIABLES
# # # # # # #
# ------------------------------------------------------------------

# get flags
PARAM=$(getopt -o "ho:n:tv:pi:g:a:s:" -l "help,output:,nsfw:,termux,view:,print,id:,tag:,type:,sort:" -n "$SCRIPT" -- "$@")

# check if getopt failed for some reason
PARAM_RC="$?"
[[ "$PARAM_RC" != "0" ]] && \
  print_err_msg "Failed to parse parameters!" $PARAM_RC

# API
WAIFU_URL="https://api.waifu.im/images"

NSFW_EXCLUSIVE_WAIFU_URL="${WAIFU_URL}?isNsfw=True"
NSFW_ALL_WAIFU_URL="${WAIFU_URL}?isNsfw=All"
NSFW_NONE_WAIFU_URL="${WAIFU_URL}?isNsfw=False"

# ------------------------------------------------------------------
# # # # # # # #
# FLAG PARSING
# # # # # # # #
# ------------------------------------------------------------------

eval set -- "$PARAM"

OUTPUT=0
OUTPUT_NAME=""

USE_ID=0
ID_OPT=""

PRINT=0

NSFW=0
NSFW_OPT=""

NSFW_VALID=(
  e
  b
  a
  n
  exclusive
  both
  all
  none
)

VIEW=0
VIEW_OPT=""

VIEW_VALID=(
  c
  s
  chafa
  sixel
)

TAG=0
TAG_OPT=""

TAG_VALID=(
  milf
  uniform
  ass
  maid
  selfies
  paizuri
  oral
  genshin-impact
  raiden-shogun
  marin-kitagawa
  mori-calliope
  kamisato-ayaka
  rem
  nami
  one-piece
  waifu
  ero
  ecchi
  oppai
  hentai
)

TYPE=0
TYPE_OPT=""

TYPE_VALID=(
  a
  s
  b
  animated
  static
  both
  all
)

SORT=0
SORT_OPT=""

SORT_VALID=(
  f
  p
  u
  n
  r
  favorites
  popular
  uploaded
  newest
  random
)

TERMUX=0

while true; do
  case "$1" in

    -h|--help)
      print_help
      exit 0
      ;;

    -o|--output)
      OUTPUT=1
      OUTPUT_NAME="$2"
      shift 2
      continue
      ;;

    -n|--nsfw)
      NSFW=1
        case "$2" in
          h|-h|help|--help)
            printf '%s\n' "
  $SCRIPT: --nsfw

  Set NSFW mode

  Valid options:

  * e (exclusive) [ Set to only NSFW media ]
  * b (both) [ Set to both NSFW and SFW media ]
  * a (all)  [ Set to both NSFW and SFW media ]
  * n (none) [ Set to no NSFW media ]
"
            exit 0
            ;;
          *)
            if nsfw_valid "$2"; then
              NSFW_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
      ;;

    -v|--view)
      VIEW=1
        case "$2" in
          h|-h|help|--help)
            printf '%s\n' "
  $SCRIPT: --view

  Set VIEW mode

  Valid options:

  * c (chafa) [ Set to view with Chafa ]
  * s (sixel) [ Set to view with Img2sixel ]
"
            exit 0
            ;;
          *)
            if view_valid "$2"; then
              VIEW_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
      ;;

    -t|--termux)
      TERMUX=1
      shift
      continue
      ;;

    -p|--print)
      PRINT=1
      shift
      continue
      ;;

    -i|--id)
      USE_ID=1
      case "$2" in
        h|-h|help|--help)
          printf '%s\n' "
$SCRIPT: --id

View an image from a specific ID ( 4-digit number )

Usage:
  $SCRIPT -i xxxx (numbers)

ID examples:
  1739, 5469, 6873, 6900, 6992, 7124, 7799, 8357

# use any other number. those are working examples, though (REAL IMAGES), so feel free to use those.
"
          exit 0
          ;;
        *)
          ID_OPT="$2"
          shift 2
          continue
          ;;
          esac
        ;;

      -g|--tag)
        TAG=1
        case "$2" in
          h|-h|help|--help)
            printf '%s\n' "
$SCRIPT: --tag

Set TAG filter

Valid tags:

      milf, uniform, ass, maid,
      waifu, ero, ecchi, oppai, hentai,
      selfies, paizuri, oral, rem,

      raiden-shogun, marin-kitagawa,
      mori-calliope, kamisato-ayaka,
      genshin-impact, nami, one-piece
      "
            exit 0
            ;;
          *)
            if tag_valid "$2"; then
              TAG_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
        ;;

      -a|--type)
        TYPE=1
        case "$2" in
          h|-h|help|--help)
            printf '%s\n' "
  $SCRIPT: --type

  Set TYPE filter (animated vs static images)

  Valid options:

    * a (animated) [ Only animated (gif) media ]
    * s (static)   [ Only static (non-gif) media ]
    * b (both), all [ Both animated and static media ]
  "
            exit 0
            ;;
          *)
            if type_valid "$2"; then
              TYPE_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
          esac
        ;;

      -s|--sort)
        SORT=1
        case "$2" in
          h|-h|help|--help)
            printf '%s\n' "
  $SCRIPT: --sort

  Set SORT order

  Valid options:

    * f (favorites), p (popular) [ Sort by most popular ]
    * u (uploaded), n (newest)   [ Sort by newest upload ]
    * r (random)                 [ Sort randomly (default if --sort is omitted) ]
  "
            exit 0
            ;;
          *)
            if sort_valid "$2"; then
              SORT_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
          esac
        ;;

    --)
      shift
      break
      ;;
    *)
      print_err_msg "Failed to parse arguments! Unknown option: $1" 1
      ;;
  esac
done

# ------------------------------------------------------------------
# # # # # # #
#   VALIDATION
# # # # # # #
# ------------------------------------------------------------------

{
  {
    COMMANDS=(
      curl
      jq
    )
    MISSING_CMD=()
    CMD_FAILED=0

    for CMD in "${COMMANDS[@]}"; do
      if ! command -v "$CMD" &>/dev/null; then
        MISSING_CMD+=("$CMD")
        CMD_FAILED=1
      fi
    done

    if [[ "$CMD_FAILED" == "1" ]]; then
      echo "$SCRIPT: Missing commands!" >&2
      printf "\n{\n"
      for MISSING in "${MISSING_CMD[@]}"; do
        printf "$MISSING\n"
      done
      printf "}\n"
      exit 1
    fi
  }
}


# ------------------------------------------------------------------
# # # # # # #
#  LOGIC
# # # # # # #
# ------------------------------------------------------------------

# set variable for URL
if [[ "$USE_ID" == "1" ]]; then
  for EXT in png jpeg jpg gif; do
    if curl -sfI -o /dev/null "https://cdn.waifu.im/${ID_OPT}.${EXT}"; then
      IMAGE_URL="https://cdn.waifu.im/${ID_OPT}.${EXT}"
      break
    fi
  done
else
  if [[ "$NSFW" != "1" ]]; then
    REQUEST_URL="$WAIFU_URL"
  else
    case "$NSFW_OPT" in
      e|exclusive)
        REQUEST_URL="$NSFW_EXCLUSIVE_WAIFU_URL"
        ;;
      a|all|b|both)
        REQUEST_URL="$NSFW_ALL_WAIFU_URL"
        ;;
      n|none)
        REQUEST_URL="$NSFW_NONE_WAIFU_URL"
        ;;
    esac
  fi

  if [[ "$TAG" == "1" ]]; then
    if [[ "$REQUEST_URL" == *"?"* ]]; then
      REQUEST_URL="${REQUEST_URL}&includedTags=${TAG_OPT}"
    else
      REQUEST_URL="${REQUEST_URL}?includedTags=${TAG_OPT}"
    fi
  fi

  if [[ "$TYPE" == "1" ]]; then
    case "$TYPE_OPT" in
      a|animated)
        TYPE_PARAM="isAnimated=True"
        ;;
      s|static)
        TYPE_PARAM="isAnimated=False"
        ;;
      b|both|all)
        TYPE_PARAM="isAnimated=All"
        ;;
    esac

    if [[ "$REQUEST_URL" == *"?"* ]]; then
      REQUEST_URL="${REQUEST_URL}&${TYPE_PARAM}"
    else
      REQUEST_URL="${REQUEST_URL}?${TYPE_PARAM}"
    fi
  fi

  if [[ "$SORT" == "1" ]]; then
    case "$SORT_OPT" in
      f|favorites|p|popular)
        SORT_PARAM="orderBy=Favorites"
        ;;
      u|uploaded|n|newest)
        SORT_PARAM="orderBy=UploadedAt"
        ;;
      r|random)
        SORT_PARAM="orderBy=Random"
        ;;
    esac

    if [[ "$REQUEST_URL" == *"?"* ]]; then
      REQUEST_URL="${REQUEST_URL}&${SORT_PARAM}"
    else
      REQUEST_URL="${REQUEST_URL}?${SORT_PARAM}"
    fi
  fi

  WAIFU_JSON=$(curl -s "$REQUEST_URL")

  # set image URL
  IMAGE_URL=$(printf '%s' "$WAIFU_JSON" | jq -r ".items[0].url")
fi

[[ -z "$IMAGE_URL" || "$IMAGE_URL" == "null" ]] && \
  print_err_msg "Failed to fetch valid image data!" 1

# save to file
if [[ "$OUTPUT" == "1" ]]; then
  if command -v wget &>/dev/null; then
    wget "$IMAGE_URL" -O "$OUTPUT_NAME"
  else
    print_err_msg "Missing command for flag -o: wget" 1
  fi
fi

# open on termux
if [[ "$TERMUX" == "1" ]]; then
  if command -v termux-open &>/dev/null; then
    termux-open "$IMAGE_URL"
  else
    print_err_msg "termux-open not available!" 1
  fi
fi

# view with chafa
if [[ "$VIEW" == "1" ]]; then
    case "$VIEW_OPT" in
      c|chafa)
        command -v chafa &>/dev/null || {
        print_err_msg "Missing command for flag -vc: chafa" 1
        }
        curl -s "$IMAGE_URL" | chafa
        ;;

      s|sixel)
        command -v img2sixel &>/dev/null || {
        print_err_msg "Missing library for flag -vs: libsixel" 1
        }

        curl -s "$IMAGE_URL" | img2sixel
        ;;
    esac
fi

# print statement
if [[ "$PRINT" == "1" ]]; then
  echo "$IMAGE_URL"
fi

# if no arguments, print url
if [[ -z "$1" && -z "$PRINT" || "$PRINT" == "0" ]]; then
  echo "$IMAGE_URL"
fi

exit 0
