#!/bin/bash
# This project is licensed under the GNU General Public License v3.0 LICENSE.

# ------------------------------------------------------------------
# # # # # # #
# CORE
# # # # # # #
# ------------------------------------------------------------------


# hushlogin-type implementation to hide script usage

KILLSWITCH="$HOME/.waifulock"
if [[ -f "$KILLSWITCH" || -d "$KILLSWITCH" || -l "$KILLSWITCH" ]]; then
  exit 0
fi


SCRIPT="$(basename "$0")" # grab script name

print_err_msg() {
  echo "$SCRIPT: $1" >&2
  exit "${2:-1}"
}


# ------------------------------------------------------------------
# # # # # # #
# FUNCTIONS
# # # # # # #
# ------------------------------------------------------------------

#### HELP FUNCTIONS ----------------------------<<<<<<<<<
print_help() {
  printf '%s\n' "
$SCRIPT is a simple CLI tool: view or download random waifu images from waifu.im.

Docs:
  $SCRIPT --help: Show this help screen
  $SCRIPT --nsfw help: Show nsfw help screen
  $SCRIPT --view help: Show image viewer help screen
  $SCRIPT --output help: Show saveas help screen
  $SCRIPT --id help: Show id lookup help screen
  $SCRIPT --tag help: Show tag lookup help screen
  $SCRIPT --exclude help: Show tag exclusion help screen
  $SCRIPT --type help: Show type sort help screen
  $SCRIPT --sort help: Show sort type help screen
  $SCRIPT --orientation help: Show orientation sort help screen

Usage examples:
  $SCRIPT -ne -o animegirl.png [ Set mode to only NSFW and save the image to ./animegirl.png ]
  $SCRIPT -nb -t [ Set mode to all (NSFW+SFW) and open it with termux-open, for termux users. ]
  $SCRIPT -ne -vc [ Set mode to only NSFW and view the image with chafa ]
  $SCRIPT -p [ Print image URL ]
  $SCRIPT -vc -ne -ghentai [ Set mode to only NSFW, search the tag hentai and view the image with chafa ]
  $SCRIPT -vc -nn -gwaifu [ Set mode to no NSFW, search the tag waifu and view the image with chafa ]

All options in action:
  $SCRIPT --nsfw=exclusive --view=chafa --tag=hentai --exclude=ecchi --type=static --sort=popular --orientation=portrait --no-print
  
# -g is equivalent to --tag
# -G is equivalent to --exclude
# -a is equivalent to --type
# -r is equivalent to --orientation

Valid flags (17):

  $SCRIPT -h/--help [ Show help screen ]
  $SCRIPT --unihelp [ Print all help screens at once ]
  $SCRIPT -t/--termux [ Android: open media with termux-open ]
  $SCRIPT -p/--print [ Print URL ]
  $SCRIPT --no-print [ Force-disable URL printing ]
  $SCRIPT --raw [ Print pre-curl waifu.im URL ]
  $SCRIPT --json [ Print pre-jq waifu.im JSON ]

  $SCRIPT -o/--output (arg required) [ Save output as filename ]
  $SCRIPT -n/--nsfw (arg required) [ Set NSFW Mode ]
  $SCRIPT -v/--view (arg required) [ Set inline image viewer mode ]
  $SCRIPT -i/--id (arg required) [ Lookat specific waifu ID ]
  $SCRIPT -g/--tag (arg required) [ Set included tag ]
  $SCRIPT -G/--exclude (arg required) [ Set excluded tag ]
  $SCRIPT -a/--type (arg required) [ Set media type ]
  $SCRIPT -s/--sort (arg required) [ Set sort type ]
  $SCRIPT -r/--orientation (arg required) [ Set orientation type ]
  $SCRIPT --print-var (arg required) [ Print internal waifu variable ]

$SCRIPT has a killswitch mechanism:
if ~/.waifulock exists, it exits with no action.
"
}

print_orientation_help() {
  printf '%s\n' "
$SCRIPT: --orientation

Set ORIENTATION filter

Valid options:

  * l (landscape) [ Landscape images only ]
  * p (portrait)  [ Portrait images only ]
  * s (square)    [ Square images only ]
  * a (all)       [ Any orientation ]
    "
}

print_nsfw_help() {
  printf '%s\n' "
$SCRIPT: --nsfw

Set NSFW mode

Valid options:

  * e (exclusive) [ Set to only NSFW media ]
  * b (both) [ Set to both NSFW and SFW media ]
  * a (all)  [ Set to both NSFW and SFW media ]
  * n (none) [ Set to no NSFW media ]
  "
}

print_view_help() {
  printf '%s\n' "
$SCRIPT: --view

Set VIEW mode

Valid options:

  * c (chafa) [ Set to view with Chafa ]
  * s (sixel) [ Set to view with Img2sixel ]
"
}

print_id_help() {
  printf '%s\n' "
$SCRIPT: --id

View an image from a specific ID ( 4-digit number )

Usage:
  $SCRIPT -i xxxx (numbers)

ID examples:
  ${ID_EX[*]}

# you can also use any other number. these are working examples, though (REAL IMAGES), so feel free to use these aswell.
"
}

print_tag_help() {
  printf '%s\n' "
$SCRIPT: --tag

Set TAG filter

Valid tags:

  milf, uniform, ass, maid,
  waifu, ero, ecchi, oppai, hentai,
  selfies, paizuri, oral, rem,

  raiden-shogun, marin-kitagawa,
  mori-calliope, kamisato-ayaka,
  genshin-impact, nami, one-piece
"
}


print_exclude_help() {
  printf '%s\n' "
$SCRIPT: --exclude

Set TAG to exclude

Valid tags:

  milf, uniform, ass, maid,
  waifu, ero, ecchi, oppai, hentai,
  selfies, paizuri, oral, rem,

  raiden-shogun, marin-kitagawa,
  mori-calliope, kamisato-ayaka,
  genshin-impact, nami, one-piece
"
}

print_type_help() {
  printf '%s\n' "
$SCRIPT: --type

Set TYPE filter (animated vs static images)

Valid options:

  * a (animated) [ Only animated (gif) media ]
  * s (static)   [ Only static (non-gif) media ]
  * b (both), all [ Both animated and static media ]
"
}

print_sort_help() {
  printf '%s\n' "
$SCRIPT: --sort

Set SORT order

Valid options:

  * f (favorites), p (popular) [ Sort by most popular ]
  * u (uploaded), n (newest)   [ Sort by newest upload ]
  * r (random)                 [ Sort randomly (default if --sort is omitted) ]
"
}

print_output_help() {
  printf '%s\n' "
$SCRIPT: --output

Save media as FILENAME.ext

Usage:

$SCRIPT -o file [ Appends extension automatically ]

"
}

#### VALIDATION FUNCTIONS ----------------------------<<<<<<<<<

name_valid() {
  local XD
  local -n X_ARR="$1"

  for XD in "${X_ARR[@]}"; do
    [[ "$XD" == "$2" ]] && return 0
  done
  return 1
}

nsfw_valid() {
  name_valid NSFW_VALID "$1" && \
    return 0
  return 1
}

view_valid() {
  name_valid VIEW_VALID "$1" && \
    return 0
  return 1
}

tag_valid() {
  name_valid TAG_VALID "$1" && \
    return 0
  return 1
}

type_valid() {
  name_valid TYPE_VALID "$1" && \
    return 0
  return 1
}

sort_valid() {
  name_valid SORT_VALID "$1" && \
    return 0
  return 1
}

orientation_valid() {
  name_valid ORIENTATION_VALID "$1" && \
    return 0
  return 1
}

# ------------------------------------------------------------------
# # # # # # #
# VARIABLES
# # # # # # #
# ------------------------------------------------------------------

# test if gnu getopt
x="$(getopt -T;echo $?)"
if ! ((x >=4)); then
  print_err_msg "Getopt is not GNU!" 1
fi

# get flags
PARAM=$(getopt -o "ho:n:tv:pi:g:a:s:r:G:" -l "help,output:,nsfw:,termux,view:,print,id:,tag:,type:,sort:,orientation:,unihelp,no-print,exclude:,print-var:,raw,json" -n "$SCRIPT" -- "$@")

# check if getopt failed for some reason
PARAM_RC="$?"
[[ "$PARAM_RC" != "0" ]] && \
  print_err_msg "Failed to parse parameters!" $PARAM_RC

# API
WAIFU_URL="https://api.waifu.im/images"

# ------------------------------------------------------------------
# # # # # # # #
# FLAG PARSING
# # # # # # # #
# ------------------------------------------------------------------

eval set -- "$PARAM"

ID_EX=(
  1739
  3119
  5469
  5943
  6162
  6873
  6900
  6992
  7124
  7727
  7799
  8357
)

OUTPUT=0
OUTPUT_NAME=""

RAW_URL=0
SHOW_JSON=0

PRINT_INT_VAR=0
INT_VAR=""

USE_ID=0
ID_OPT=""

PRINT=0
DEL_PRINT=0

NSFW=0
NSFW_OPT=""

NSFW_VALID=(
  e
  b
  a
  n
  exclusive
  both
  all
  none
)

VIEW=0
VIEW_OPT=""

VIEW_VALID=(
  c
  s
  chafa
  sixel
)

TAG=0
TAG_OPTS=()

EXCLUDE=0
EXCLUDE_OPTS=()

TAG_VALID=(
  milf
  uniform
  ass
  maid
  selfies
  paizuri
  oral
  genshin-impact
  raiden-shogun
  marin-kitagawa
  mori-calliope
  kamisato-ayaka
  rem
  nami
  one-piece
  waifu
  ero
  ecchi
  oppai
  hentai
)

TYPE=0
TYPE_OPT=""

TYPE_VALID=(
  a
  s
  b
  animated
  static
  both
  all
)

SORT=0
SORT_OPT=""

SORT_VALID=(
  f
  p
  u
  n
  r
  favorites
  popular
  uploaded
  newest
  random
)

ORIENTATION=0
ORIENTATION_OPT=""

ORIENTATION_VALID=(
  l
  p
  s
  a
  landscape
  portrait
  square
  all
)

TERMUX=0

while true; do
  case "$1" in

    --raw)
      RAW_URL=1
      shift
      continue
      ;;

    --json)
      SHOW_JSON=1
      shift
      continue
      ;;

    --print-var)
      PRINT_INT_VAR=1

      INT_VAR="$2"
      typeset -n NAME_VAR="$2"
      
      shift 2
      continue
      ;;


    -h|--help)
      print_help
      exit 0
      ;;

    -o|--output)
      OUTPUT=1
      case "$2" in
        -h|--help)
          print_output_help
          exit 0
          ;;
      esac
      OUTPUT_NAME="$2"
      shift 2
      continue
      ;;

    -n|--nsfw)
      NSFW=1
        case "$2" in
          h|-h|help|--help)
            print_nsfw_help
            exit 0
            ;;
          *)
            if nsfw_valid "$2"; then
              NSFW_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
      ;;

    -v|--view)
      VIEW=1
        case "$2" in
          h|-h|help|--help)
            print_view_help
            exit 0
            ;;
          *)
            if view_valid "$2"; then
              VIEW_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
      ;;

    -t|--termux)
      TERMUX=1
      shift
      continue
      ;;

    -p|--print)
      PRINT=1
      shift
      continue
      ;;

    --no-print)
      DEL_PRINT=1
      PRINT=0
      shift
      continue
      ;;

    -i|--id)
      USE_ID=1
      case "$2" in
        h|-h|help|--help)
          print_id_help
          exit 0
          ;;
        *)
          ID_OPT="$2"
          shift 2
          continue
          ;;
          esac
        ;;

      -g|--tag)
        TAG=1
        case "$2" in
          h|-h|help|--help)
            print_tag_help
            exit 0
            ;;
          *)
            if tag_valid "$2"; then
              TAG_OPTS+=("$2")
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
        ;;

      -a|--type)
        TYPE=1
        case "$2" in
          h|-h|help|--help)
            print_type_help
            exit 0
            ;;
          *)
            if type_valid "$2"; then
              TYPE_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
          esac
        ;;

      -s|--sort)
        SORT=1
        case "$2" in
          h|-h|help|--help)
            print_sort_help
            exit 0
            ;;
          *)
            if sort_valid "$2"; then
              SORT_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
          esac
        ;;

      -r|--orientation)
        ORIENTATION=1
        case "$2" in
          h|-h|help|--help)
            print_orientation_help
            exit 0
            ;;
          *)
            if orientation_valid "$2"; then
              ORIENTATION_OPT="$2"
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
          esac
        ;;

      -G|--exclude)
        EXCLUDE=1
        case "$2" in
          h|-h|help|--help)
            print_exclude_help
            exit 0
            ;;
          *)
            if tag_valid "$2"; then
              EXCLUDE_OPTS+=("$2")
              shift 2
              continue
            else
              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
            fi
            ;;
        esac
        ;;

      --unihelp)
        print_help
        echo "--------------------------------"
        print_nsfw_help
        echo "--------------------------------"
        print_view_help
        echo "--------------------------------"
        print_output_help
        echo "--------------------------------"
        print_id_help
        echo "--------------------------------"
        print_tag_help
        echo "--------------------------------"
        print_exclude_help
        echo "--------------------------------"
        print_type_help
        echo "--------------------------------"
        print_sort_help
        echo "--------------------------------"
        print_orientation_help
        exit 0
        ;;

    --)
      shift
      break
      ;;
    *)
      print_err_msg "Failed to parse arguments! Unknown option: $1" 1
      ;;
  esac
done

# ------------------------------------------------------------------
# # # # # # #
#   VALIDATION
# # # # # # #
# ------------------------------------------------------------------

{
  {
    COMMANDS=(
      curl
      jq
    )
    MISSING_CMD=()
    CMD_FAILED=0

    for CMD in "${COMMANDS[@]}"; do
      if ! command -v "$CMD" &>/dev/null; then
        MISSING_CMD+=("$CMD")
        CMD_FAILED=1
      fi
    done

    if [[ "$CMD_FAILED" == "1" ]]; then
      echo "$SCRIPT: Missing commands!" >&2
      printf "\n{\n"
      for MISSING in "${MISSING_CMD[@]}"; do
        printf "$MISSING\n"
      done
      printf "}\n"
      exit 1
    fi
  }
}


# ------------------------------------------------------------------
# # # # # # #
#  LOGIC
# # # # # # #
# ------------------------------------------------------------------

# set variable for URL
if [[ "$USE_ID" == "1" ]]; then
  for EXT in png jpeg jpg gif; do
    if curl -sfI -o /dev/null "https://cdn.waifu.im/${ID_OPT}.${EXT}"; then
      IMAGE_URL="https://cdn.waifu.im/${ID_OPT}.${EXT}"
      break
    fi
  done
else
  QUERY_PARAMS=()

  if [[ "$NSFW" == "1" ]]; then
    case "$NSFW_OPT" in
      e|exclusive) QUERY_PARAMS+=("isNsfw=True") ;;
      a|all|b|both) QUERY_PARAMS+=("isNsfw=All") ;;
      n|none) QUERY_PARAMS+=("isNsfw=False") ;;
    esac
  fi

  for TAG_ITEM in "${TAG_OPTS[@]}"; do
    QUERY_PARAMS+=("includedTags=${TAG_ITEM}")
  done

  if [[ "$TYPE" == "1" ]]; then
    case "$TYPE_OPT" in
      a|animated) QUERY_PARAMS+=("isAnimated=True") ;;
      s|static) QUERY_PARAMS+=("isAnimated=False") ;;
      b|both|all) QUERY_PARAMS+=("isAnimated=All") ;;
    esac
  fi

  if [[ "$SORT" == "1" ]]; then
    case "$SORT_OPT" in
      f|favorites|p|popular) QUERY_PARAMS+=("orderBy=Favorites") ;;
      u|uploaded|n|newest) QUERY_PARAMS+=("orderBy=UploadedAt") ;;
      r|random) QUERY_PARAMS+=("orderBy=Random") ;;
    esac
  fi

  if [[ "$ORIENTATION" == "1" ]]; then
    case "$ORIENTATION_OPT" in
      l|landscape) QUERY_PARAMS+=("orientation=Landscape") ;;
      p|portrait) QUERY_PARAMS+=("orientation=Portrait") ;;
      s|square) QUERY_PARAMS+=("orientation=Square") ;;
      a|all) QUERY_PARAMS+=("orientation=All") ;;
    esac
  fi

  for EXCLUDE_ITEM in "${EXCLUDE_OPTS[@]}"; do
    QUERY_PARAMS+=("excludedTags=${EXCLUDE_ITEM}")
  done

  if [[ ${#QUERY_PARAMS[@]} -gt 0 ]]; then
    QUERY_STRING=$(IFS='&'; echo "${QUERY_PARAMS[*]}")
    REQUEST_URL="${WAIFU_URL}?${QUERY_STRING}"
  else
    REQUEST_URL="$WAIFU_URL"
  fi

  WAIFU_JSON=$(curl -s "$REQUEST_URL")

  # set image URL
  IMAGE_URL=$(printf '%s' "$WAIFU_JSON" | jq -r ".items[0].url")
fi



if [[ "$RAW_URL" != "1" && "$SHOW_JSON" != "1" ]]; then

  [[ -z "$IMAGE_URL" || "$IMAGE_URL" == "null" || ! "$IMAGE_URL" =~ ^https:\/\/cdn\.waifu\.im\/ ]] && \
    print_err_msg "Failed to fetch valid image data!" 1

  # check if no-print was passed
  if [[ "$DEL_PRINT" == "1" ]]; then
    PRINT=0
  fi

  # save to file
  if [[ "$OUTPUT" == "1" ]]; then
    if command -v wget &>/dev/null; then
      E_EXT="${IMAGE_URL:26}"
      wget "$IMAGE_URL" -O "${OUTPUT_NAME}.${E_EXT}"
    else
      print_err_msg "Missing command for flag -o: wget" 1
    fi
  fi

  # open on termux
  if [[ "$TERMUX" == "1" ]]; then
    if command -v termux-open &>/dev/null; then
      termux-open "$IMAGE_URL"
    else
      print_err_msg "termux-open not available!" 1
    fi
  fi

  # view with chafa
  if [[ "$VIEW" == "1" ]]; then
    case "$VIEW_OPT" in
      c|chafa)
        command -v chafa &>/dev/null || {
        print_err_msg "Missing command for flag -vc: chafa" 1
        }
        curl -s "$IMAGE_URL" | chafa
        ;;

      s|sixel)
        command -v img2sixel &>/dev/null || {
        print_err_msg "Missing library for flag -vs: libsixel" 1
        }

        curl -s "$IMAGE_URL" | img2sixel
        ;;
    esac
  fi

  # print statement
  if [[ "$PRINT" == "1" ]]; then
    echo "$IMAGE_URL"
  fi

  # if no arguments, print url
  if [[ -z "$1" && -z "$PRINT" || "$PRINT" == "0" ]]; then
    if [[ "$DEL_PRINT" == "1" ]]; then
      :
    else
      echo "$IMAGE_URL"
    fi
  fi

else
  if [[ "$RAW_URL" == "1" ]]; then
    echo "$REQUEST_URL"
  fi
  echo
  if [[ "$SHOW_JSON" == "1" ]]; then
    echo "$WAIFU_JSON"
  fi
fi


if [[ "$PRINT_INT_VAR" == "1" ]]; then
  if [[ -z "$NAME_VAR" ]]; then
    print_err_msg "Variable not found!"
  else
    if declare -p "$INT_VAR" 2>/dev/null | grep -q '^declare -a'; then
      for VAR in "${NAME_VAR[@]}"; do
        printf '%s\n' "$VAR"
      done
    else
      echo "$NAME_VAR"
    fi
  fi
fi

exit 0
